# Generated by Django 5.1.2 on 2024-11-09 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippingapp', '0003_remove_order_order_date_order_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shippingapp.order_confirm'),
        ),
    ]
