# Generated by Django 5.1.2 on 2024-11-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shippingapp', '0010_alter_order_confirm_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_confirm',
            name='order_id',
        ),
    ]
